### ISSUE TITLE
page 5 keystone-manage command: missing sudo?

### ISSUE THREAD

**Issue by flavio-fernandes** [OpenStackCookbook/OpenStackCookbook#62]
Hello,

The last command on page 5:
keystone-manage ssl_setup --keystone-user keystone --keystone-group keystone

Gives me the following error, unless I use 'sudo'. Is that something thast should be in the errata?

Thanks,

-- flavio

vagrant@controller:~$ keystone-manage ssl_setup --keystone-user keystone --keystone-group keystone
2015-11-16 16:23:07.821 12236 WARNING keystone.cli [-] keystone-manage ssl_setup is not recommended for production use.
2015-11-16 16:23:07.882 12236 CRITICAL keystone [-] EnvironmentError: makedirs('/etc/keystone/ssl/certs'): Permission denied
2015-11-16 16:23:07.882 12236 TRACE keystone Traceback (most recent call last):
2015-11-16 16:23:07.882 12236 TRACE keystone   File "/usr/bin/keystone-manage", line 44, in <module>
2015-11-16 16:23:07.882 12236 TRACE keystone     cli.main(argv=sys.argv, config_files=config_files)
2015-11-16 16:23:07.882 12236 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/cli.py", line 307, in main
2015-11-16 16:23:07.882 12236 TRACE keystone     CONF.command.cmd_class.main()
2015-11-16 16:23:07.882 12236 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/cli.py", line 165, in main
2015-11-16 16:23:07.882 12236 TRACE keystone     conf_ssl.run()
2015-11-16 16:23:07.882 12236 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/common/openssl.py", line 204, in run
2015-11-16 16:23:07.882 12236 TRACE keystone     self.build_ssl_config_file()
2015-11-16 16:23:07.882 12236 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/common/openssl.py", line 105, in build_ssl_config_file
2015-11-16 16:23:07.882 12236 TRACE keystone     group=self.use_keystone_group, log=LOG)
2015-11-16 16:23:07.882 12236 TRACE keystone   File "/usr/lib/python2.7/dist-packages/keystone/common/utils.py", line 484, in make_dirs
2015-11-16 16:23:07.882 12236 TRACE keystone     raise EnvironmentError("makedirs('%s'): %s" % (path, exc.strerror))
2015-11-16 16:23:07.882 12236 TRACE keystone EnvironmentError: makedirs('/etc/keystone/ssl/certs'): Permission denied
2015-11-16 16:23:07.882 12236 TRACE keystone
vagrant@controller:~$ sudo keystone-manage ssl_setup --keystone-user keystone --keystone-group keystone
2015-11-16 16:23:22.295 12245 WARNING keystone.cli [-] keystone-manage ssl_setup is not recommended for production use.
vagrant@controller:~$

**Comment by flavio-fernandes** [comment]
heh, it looks like so:
https://github.com/OpenStackCookbook/OpenStackCookbook/blob/master/controller.sh#L93

**Comment by uksysadmin** [comment]
Submitted to Packt to add to book errata.
