### ISSUE TITLE
MySQL connection error

### ISSUE THREAD

**Issue by boopathi** [OpenStackCookbook/OpenStackCookbook#9]
During cinder installation, 

```
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
     * Setting up iSCSI targets
   ...done.
2013-12-02 11:56:28  WARNING [cinder.db.sqlalchemy.session] SQL connection failed. 10 attempts left.
2013-12-02 11:56:41  WARNING [cinder.db.sqlalchemy.session] SQL connection failed. 9 attempts left.
2013-12-02 11:56:54  WARNING [cinder.db.sqlalchemy.session] SQL connection failed. 8 attempts left.
2013-12-02 11:57:07  WARNING [cinder.db.sqlalchemy.session] SQL connection failed. 7 attempts left.
2013-12-02 11:57:20  WARNING [cinder.db.sqlalchemy.session] SQL connection failed. 6 attempts left.
2013-12-02 11:57:33  WARNING [cinder.db.sqlalchemy.session] SQL connection failed. 5 attempts left.
2013-12-02 11:57:46  WARNING [cinder.db.sqlalchemy.session] SQL connection failed. 4 attempts left.
2013-12-02 11:57:59  WARNING [cinder.db.sqlalchemy.session] SQL connection failed. 3 attempts left.
2013-12-02 11:58:12  WARNING [cinder.db.sqlalchemy.session] SQL connection failed. 2 attempts left.
2013-12-02 11:58:25  WARNING [cinder.db.sqlalchemy.session] SQL connection failed. 1 attempts left.
2013-12-02 11:58:38 CRITICAL [cinder] (OperationalError) (2003, "Can't connect to MySQL server on '172.30.0.200' (113)") None None
Traceback (most recent call last):
  File "/usr/bin/cinder-manage", line 794, in <module>
    main()
  File "/usr/bin/cinder-manage", line 791, in main
    fn(*fn_args)
  File "/usr/bin/cinder-manage", line 219, in sync
    return migration.db_sync(version)
  File "/usr/lib/python2.7/dist-packages/cinder/db/migration.py", line 33, in db_sync
    return IMPL.db_sync(version=version)
  File "/usr/lib/python2.7/dist-packages/cinder/db/sqlalchemy/migration.py", line 76, in db_sync
    current_version = db_version()
  File "/usr/lib/python2.7/dist-packages/cinder/db/sqlalchemy/migration.py", line 88, in db_version
    return versioning_api.db_version(get_engine(), repository)
  File "/usr/lib/python2.7/dist-packages/cinder/db/sqlalchemy/session.py", line 138, in get_engine
    _ENGINE.connect()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2471, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 878, in __init__
    self.__connection = connection or engine.raw_connection()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2557, in raw_connection
    return self.pool.unique_connection()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 184, in unique_connection
    return _ConnectionFairy(self).checkout()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 401, in __init__
    rec = self._connection_record = pool._do_get()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 746, in _do_get
    con = self._create_connection()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 189, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 282, in __init__
    self.connection = self.__connect()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 344, in __connect
    connection = self.__pool._creator()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 80, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 281, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (OperationalError) (2003, "Can't connect to MySQL server on '172.30.0.200' (113)") None None
0+0 records in
0+0 records out
0 bytes (0 B) copied, 1.2862e-05 s, 0.0 kB/s
  Physical volume "/dev/loop2" successfully created
  Volume group "cinder-volumes" successfully created
cinder-api stop/waiting
cinder-api start/running, process 18907
cinder-scheduler stop/waiting
cinder-scheduler start/running, process 18918
stop: Unknown instance: 
cinder-volume start/running, process 18929
```

**Comment by mhdchebab** [comment]
Re-install python-openstackclient.
add a line in hosts file:
127.0.0.1      controller

It worked for me.
